### ISSUE TITLE
Add a Title to the lading page

### ISSUE THREAD

**Issue by ChonPaSa** [ChonPaSa/ContributionTest#2]
in index.html add a the title "Contribution Test"

**Comment by clockclog** [comment]
Hi! I'll add it in

**Comment by ChonPaSa** [comment]
Thanks clocklog! fell free to create issues PR,....

**Comment by ChonPaSa** [comment]
I merged the change but I think it is always a good idea to create a new branch for the changes that you do. Trying to learn here too :) Thanks and keep playing
